In [31]:
import pandas as pd

tracker = pd.read_csv("jobs2.csv")

tracker

,geometry,crs,temporal_extent,EC_hcat_n,id,backend_name,status,start_time,running_start_time,cpu,memory,duration
0,"POLYGON ((26.92823823 57.91994291, 26.92845798...",EPSG:4326,"['2024-01-01', '2024-03-01']",carrots_daucus,j-250523094750432baf942d239442f06c,cdse,finished,2025-05-23T09:47:50Z,NaN,168.870104899 cpu-seconds,1132107.134765625 mb-seconds,123 seconds
1,"POLYGON ((24.55664049 59.35187675, 24.55664043...",EPSG:4326,"['2024-01-01', '2024-03-01']",carrots_daucus,j-25052309480742508f158e885e6a7bc0,cdse,finished,2025-05-23T09:48:07Z,NaN,167.030492303 cpu-seconds,946286.80078125 mb-seconds,134 seconds
2,"POLYGON ((23.03543225 58.53201079, 23.03543471...",EPSG:4326,"['2024-01-01', '2024-03-01']",carrots_daucus,j-2505230948244d9da1e1ed845ae786aa,cdse,finished,2025-05-23T09:48:24Z,NaN,177.640452705 cpu-seconds,821055.744140625 mb-seconds,127 seconds
3,"POLYGON ((24.54440459 59.25171536, 24.54439138...",EPSG:4326,"['2024-01-01', '2024-03-01']",carrots_daucus,j-2505230948404acfb6d08c083bb1d368,cdse,finished,2025-05-23T09:48:40Z,NaN,112.19843260799999 cpu-seconds,545842.333984375 mb-seconds,115 seconds
4,"POLYGON ((24.58255816 59.25572876, 24.58252244...",EPSG:4326,"['2024-01-01', '2024-03-01']",carrots_daucus,j-2505230949004202aaa0e047649e3bbe,cdse,running,2025-05-23T09:49:00Z,2025-05-23T09:51:45Z,NaN,NaN,NaN
5,"POLYGON ((25.45059328 58.15444129, 25.45063731...",EPSG:4326,"['2024-01-01', '2024-03-01']",carrots_daucus,j-250523094916469cbabc52073d3ec5a0,cdse,running,2025-05-23T09:49:17Z,2025-05-23T09:51:45Z,NaN,NaN,NaN
6,"POLYGON ((25.78558625 58.83768046, 25.7856111 ...",EPSG:4326,"['2024-01-01', '2024-03-01']",carrots_daucus,j-25052309493346379e13d9d119e05325,cdse,running,2025-05-23T09:49:33Z,2025-05-23T09:51:46Z,NaN,NaN,NaN
7,"POLYGON ((24.53412315 59.25222566, 24.5322492 ...",EPSG:4326,"['2024-01-01', '2024-03-01']",carrots_daucus,j-2505230949504c6384d4a495e3832729,cdse,running,2025-05-23T09:49:50Z,2025-05-23T09:51:46Z,NaN,NaN,NaN
8,"POLYGON ((26.02975603 58.48202123, 26.02986464...",EPSG:4326,"['2024-01-01', '2024-03-01']",carrots_daucus,j-250523095007465b9bc9fcb21efe2c52,cdse,running,2025-05-23T09:50:07Z,2025-05-23T09:51:46Z,NaN,NaN,NaN
9,"POLYGON ((25.11915033 59.26681075, 25.11917935...",EPSG:4326,"['2024-01-01', '2024-03-01']",carrots_daucus,j-25052309502340279eaa02889f03cc4e,cdse,queued,2025-05-23T09:50:23Z,NaN,NaN,NaN,NaN
10,"POLYGON ((24.17097701 58.61711298, 24.17103009...",EPSG:4326,"['2024-01-01', '2024-03-01']",spelt,j-25052309514848679c8a00a2a073cc46,cdse,created,2025-05-23T09:51:48Z,NaN,NaN,NaN,NaN
11,"POLYGON ((24.17157628 58.61716049, 24.17161896...",EPSG:4326,"['2024-01-01', '2024-03-01']",spelt,j-2505230952064aa3835762fad7e14c55,cdse,created,2025-05-23T09:52:06Z,NaN,NaN,NaN,NaN
12,"POLYGON ((25.04255783 59.02648479, 25.04251194...",EPSG:4326,"['2024-01-01', '2024-03-01']",spelt,j-2505230952244060a337e6c1f2f59775,cdse,created,2025-05-23T09:52:24Z,NaN,NaN,NaN,NaN
13,"POLYGON ((25.04701078 59.02669566, 25.0523183 ...",EPSG:4326,"['2024-01-01', '2024-03-01']",spelt,j-250523095240473a9f0b5bbf83a35727,cdse,created,2025-05-23T09:52:40Z,NaN,NaN,NaN,NaN
14,"POLYGON ((25.046909 59.00348961, 25.04900312 5...",EPSG:4326,"['2024-01-01', '2024-03-01']",spelt,NaN,NaN,not_started,NaN,NaN,NaN,NaN,NaN
15,"POLYGON ((26.60813758 58.27401347, 26.6141803 ...",EPSG:4326,"['2024-01-01', '2024-03-01']",spelt,NaN,NaN,not_started,NaN,NaN,NaN,NaN,NaN
16,"POLYGON ((23.53527929 58.86937141, 23.53532324...",EPSG:4326,"['2024-01-01', '2024-03-01']",spelt,NaN,NaN,not_started,NaN,NaN,NaN,NaN,NaN
17,"POLYGON ((26.57386945 58.26646854, 26.57403923...",EPSG:4326,"['2024-01-01', '2024-03-01']",spelt,NaN,NaN,not_started,NaN,NaN,NaN,NaN,NaN
18,"POLYGON ((24.34591759 58.61612633, 24.34602406...",EPSG:4326,"['2024-01-01', '2024-03-01']",spelt,NaN,NaN,not_started,NaN,NaN,NaN,NaN,NaN
19,"POLYGON ((26.75301697 58.66852668, 26.75299193...",EPSG:4326,"['2024-01-01', '2024-03-01']",spelt,NaN,NaN,not_started,NaN,NaN,NaN,NaN,NaN